# Copyright 2012 United States Government, as represented by the Secretary of Defense, Under
# Secretary of Defense (Personnel & Readiness).
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.

require "rake"
require "rake/clean"
require "tilt"
require "yaml"


CLOBBER.include('/web/**/*.html')
CLOBBER.include('/web/*.html')


task :default => [ :clean, :clobber, :web ]

desc "Generate the catalog and documentation."

task :build do 
end
task :full do 
end

task :clean do 
	# Clean the web folders of generated html
	sh "rm -rf web/*.html web/**/*.html"
end


task :web => "web/catalog.html"  do

    # Add the build tools to the path.
    original_path = ENV["PATH"]
    ENV["PATH"] = File.expand_path( "../support/build/Pygments-1.4" ) + ":" + ENV["PATH"]
	
    # Render the Markdown.

    FileList[ "web/*.md" ].each do |md|
        if md == "web/about.md"
            sh "( cat web/format/preamble ; kramdown 'web/format/carousel.md' ;  kramdown 'web/about.md' ; cat web/format/postamble ) > 'web/about.html'"
        elsif md == "web/documentation.md"
            sh "( cat web/format/preamble ; cat web/format/docs.preamble ; kramdown 'web/documentation.md' ; cat web/format/docs.postamble ; cat web/format/postamble ) > 'web/documentation.html'"
        else # web/forum.md
            sh "( cat web/format/preamble ; kramdown '#{md}' ; cat web/format/postamble ) > '#{ md.ext ".html" }'"
        end
    end

    # Render the catalog pages (web/catalog.htm & web/gallery.htm)

    FileList[ "web/*.htm" ].each do |htm|
        sh "( cat web/format/preamble ; cat '#{htm}' ; cat web/format/postamble ) > '#{ htm.ext ".html" }'"
    end

    # Render the documentation pages

    FileList[ "web/docs/**/*.md" ].each do |md|
        sh "( cat web/docs/format/preamble ; kramdown '#{md}' ; cat web/docs/format/postamble ) > '#{ md.ext ".html" }'"
    end

    # Restore the path.

    ENV["PATH"] = original_path

end